### ISSUE TITLE
Selecting the same index does not update browser panel

### ISSUE THREAD

**Issue by m4dkip** [CS2103-AY1819S1-F10-4/main#203]
**Describe the bug**
If the same index is selected on 2 different Lists, swapping between the panels does not update the browser panel.

**To Reproduce**
1. Have 2 populated lists
2. Select index 1 from list 1 (sr 1)
3. Select index 1 from list 2 (si 1)
4. Select index 1 from list 1 (sr 1)
5. Select index 1 from list 2 (si 1)
6. Observe that the browser panel is not updating properly. 

**Expected behavior**
Browser panel should update when swapping between different Lists.

**Comment by AZhiKai** [comment]
This bug doesn't seem to happen if I have 2 items, but 1 reservation. Hmm.. 🤔

**Comment by AZhiKai** [comment]
Found the cause:

Basically, when we `si 1` then `sr 1` then `si 1` again, to the listener, the item is still the same (aka item 1 == item 1), so it doesn't bother firing the `ItemPanelSelectionChangedEvent` event. The same thing happens when you click item 1, then click it again and you will realise the event doesn't fire as well. 

Looking into a fix.
