### ISSUE TITLE
Reservation timestamp should be validated

### ISSUE THREAD

**Issue by AZhiKai** [CS2103-AY1819S1-F10-4/main#207]
**Describe the bug**
Creating reservation can allow us to input timestamp that has already passed. 

**To Reproduce**
1. Look at current timestamp
2. Attempt to add a reservation whose timestamp has already passed, and it gets successfully added.

**Expected behavior**
Do not allow reservation to be added if timestamp has already passed current timestamp.

We assume using system time.

**Comment by m4dkip** [comment]
I believe we should relax the limitation to `Date` only, and still allow the user to add/edit `Time` values that are within the same day.

This is because customers might be late (maybe by a few minutes or hours) and the user might want to shift their times forward even if the time has already passed.

**Comment by AZhiKai** [comment]
But normally wouldn't a reservation been made in advance?

**Comment by m4dkip** [comment]
I will have to think about this aspect more...

(Also, second reason is that, given the current implementation of my `Date` and `Time`, since they are split up, 

I foresee that the implementation of the time check is going be a bit messy to check BOTH `Date` and `Time` when user wishes to edit the `Time` field only)

**Comment by AZhiKai** [comment]
Understandable, If there's insufficient time, can carry on with your current implementation but do state it in the UG/DG (wherever appropriate) so the testers wouldn't think this is a bug, but rather, a feature. 😄
